"use client";

import { Card, CardContent, CardHeader } from "@/components/atoms/Card";
import { ClientGeneration } from "@/components/atoms/ClientGeneration";
import { GlobeIcon } from "@radix-ui/react-icons";
import { useState } from "react";
import { motion } from "framer-motion";
import {
  TooltipProvider,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
} from "@/components/atoms/Tooltip";

export const SearchQueryAnswer = ({
  sources,
  searchQuery,
}: {
  sources: any;
  searchQuery: string;
}) => {
  const [isLoading, setIsLoading] = useState(false);
  return (
    <Card>
      <CardHeader size={4}>
        <span className="flex flex-row gap-2 items-end">
          Answer
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger>
                <motion.div
                  animate={{ rotate: isLoading ? 360 : 0 }}
                  transition={{
                    duration: 1,
                    repeat: isLoading ? Infinity : 0,
                    ease: "easeInOut",
                  }}
                >
                  <GlobeIcon className="h-8" />
                </motion.div>
              </TooltipTrigger>
              <TooltipContent>
                <p>Generated by AI using real sources</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </span>
      </CardHeader>
      <CardContent>
        <ClientGeneration
          useMarkdown={true}
          sources={sources}
          messages={[{ role: "user", content: searchQuery }]}
          setIsLoading={setIsLoading}
        />
      </CardContent>
    </Card>
  );
};
