import classNames from "classnames";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/atoms/HoverCard";
import { Button } from "./Button";
import { Popover, PopoverContent, PopoverTrigger } from "./Popover";
import { useState } from "react";
import { ClientGeneration } from "./ClientGeneration";
import {
  MagicWandIcon,
  QuestionMarkIcon,
  Pencil1Icon,
  FilePlusIcon,
} from "@radix-ui/react-icons";
import Markdown from "react-markdown";

export const SocraticText = ({
  text,
  className,
  disabled,
}: {
  text: string;
  className?: string;
  disabled?: boolean;
}) => {
  const [mode, setMode] = useState<"nuance" | "critique" | "none">("none");

  return (
    <Popover>
      <PopoverTrigger asChild>
        <span
          className={classNames(
            "hover:bg-neutral-50 transition-all duration-200 cursor-pointer text-left p-2 rounded-md",
            className
          )}
        >
          <Markdown>{text}</Markdown>
        </span>
      </PopoverTrigger>
      {/* TODO: add icons */}
      {!disabled && (
        <PopoverContent
          className={classNames(
            "bg-beige-50 z-50 flex flex-col gap-2 text-sm text-left p-1",
            {
              "w-[400px]": mode !== "none",
              "w-[200px]": mode === "none",
            }
          )}
        >
          {mode === "none" && (
            <>
              <span
                className="w-full flex flex-row gap-2 items-center rounded-md bg-beige-50 hover:bg-neutral-50 transition-all duration-200 p-2 text-sm cursor-pointer"
                onClick={() => setMode("nuance")}
              >
                <FilePlusIcon className="h-4 w-4" /> Add nuance
              </span>
              <span
                className="w-full flex flex-row gap-2 items-center rounded-md bg-beige-50 hover:bg-neutral-50 transition-all duration-200 p-2 text-sm cursor-pointer"
                onClick={() => setMode("critique")}
              >
                <Pencil1Icon className="h-4 w-4" /> Critique
              </span>
            </>
          )}
          {mode === "nuance" && (
            <div className="flex flex-col gap-2">
              <span className="text-xs flex flex-row gap-2 font-semibold">
                <MagicWandIcon /> Nuance (generated by AI)
              </span>
              <ClientGeneration
                messages={[
                  {
                    role: "system",
                    content:
                      "Your job is to add unbiased nuance to the text that the user sends. Use no more than 100 words. Please help them understand the topic more in-depth.",
                  },
                  { role: "user", content: text },
                ]}
                socratic={false}
              />
            </div>
          )}
          {mode === "critique" && (
            <div className="flex flex-col gap-2">
              <span className="text-xs flex flex-row gap-2 font-semibold">
                <MagicWandIcon /> Critique (generated by AI)
              </span>
              <ClientGeneration
                messages={[
                  {
                    role: "system",
                    content:
                      "Your job is to critique the text that the user sends. Use no more than 100 words. Please criticize all relevant points in a level-headed and educational manner.",
                  },
                  { role: "user", content: text },
                ]}
                socratic={false}
              />
            </div>
          )}
        </PopoverContent>
      )}
    </Popover>
  );
};
